server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: movies-service
          uri: lb://movies-service
          predicates:
            - Path=/api/v1/addresses/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/addresses/**
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/api/v1/addresses/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: none
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
