global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'movies-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['movies-service:8081'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'business-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['business-service:8082'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8083'] ## only for demo purposes don't use host.docker.internal in production